### PR TITLE
check that properties is an array before accessing

### LINKED ISSUE #196: [error] PHP Fatal error:  Cannot use object of type stdClass as array
```
PHP Fatal error:  Cannot use object of type stdClass as array in vendor/mf2/mf2/Mf2/Parser.php on line 1412
```
encountered while parsing this URL: https://www.eatthispodcast.com/our-daily-bread-22/

### PR DESCRIPTION
**Pull request by aaronpk**
fixes #196

### CODE REVIEW

File: tests/Mf2/ParserTest.php [hunk 1]
```diff
@@ -824,5 +824,22 @@ public function testNotMutatingPassedInDOM() {
...
+<div class="h-entry">
+  <li class="h-cite u-comment">
+    <div class="vcard"></div>
+  </li>
+</div>
+EOD;
+
+		$output = Mf2\parse($input);
+		$this->assertEquals([], $output['items'][0]['properties']['comment'][0]['properties']);
+		$this->assertEquals([], $output['items'][0]['properties']['comment'][0]['children'][0]['properties']);
```
Comment (gRegorLove) [inline tests/Mf2/ParserTest.php]: Minor update: can use `assertEmpty()` for these.

Comment (aaronpk) [reply tests/Mf2/ParserTest.php]: what does `assertEmpty` do if the value is null or not an array? I want to ensure that `properties` exists and is an array with no items.

Comment (gRegorLove) [reply tests/Mf2/ParserTest.php]: I think null value would pass the assertion; not sure about an empty object. [assertInternalType](https://phpunit.de/manual/6.5/en/appendixes.assertions.html#appendixes.assertions.assertInternalType) can be used to verify it's an array.
