### PR TITLE
Fix hreview backcompat

### LINKED ISSUE #155: hreview backcompat
php-mf2 does not do `hreview` backcompat see: http://microformats.org/wiki/h-review#Parser_Compatibility

# Example

## HTML
```html
    <article class="hreview">
<a class="url" href="http://example.com">URL</a>
    </article>
```

## Current Output

```json
    "items": [
        {
            "type": [
                "h-review"
            ],
            "properties": []
        }
    ]
```
## Expected output

```json
    "items": [
        {
            "type": [
                "h-review"
            ], 
            "properties": {
                "url": [
                    "http://example.com"
                ]
            }
        }
    ]
```

### PR DESCRIPTION
**Pull request by gRegorLove**
Fixes #155 

- rel="self bookmark" -> u-url
- class="reviewer" -> p-author h-card
- fix class="item hproduct", was backcompat parsing as vevent instead of hproduct
- adds unit tests
- comment out a unit test that was not making any assertions or failures.
- fix some syntax/warnings in newer versions of PHPUnit

### CODE REVIEW

File: tests/Mf2/ParserTest.php [hunk 1]
```diff
@@ -139,6 +139,8 @@ public function testParseEWithWhitespace() {
 	 * @group parseH
 	 */
 	public function testInvalidClassnamesContainingHAreIgnored() {
+		self::expectNotToPerformAssertions();
```
Comment (artlung) [inline tests/Mf2/ParserTest.php:142]: So is this a test that succeeds if no assertions are performed? I must be misunderstanding it.

**Review by artlung — APPROVED** [review]

File: tests/Mf2/ParserTest.php (hunk 1 above)
Comment (artlung) [reply tests/Mf2/ParserTest.php:142]: I'm more used to an assertion that a string is not present or not equal or not contains, but that works.

**Review by tantek — CHANGES_REQUESTED** [review]
Should we switch from indiewebcamp.com references to indieweb.org and use https instead (including example.com URLs)?

**Comment by gRegorLove** [comment]
Updated indieweb.org URL and https://example.com in tests.

Updated the test @artlung brought up so it has an assertion of no matches instead of calling fail() if a match is found.

**Review by tantek — APPROVED** [review]
